### ISSUE TITLE
"message: no implicit conversion of Pathname into String" on Docker compose restart

### ISSUE THREAD

**Issue by fanpu** [autolab/Autolab#1265]
On second startup with the Docker compose installation, we get the following error:

![DeepinScreenshot_select-area_20201210224458](https://user-images.githubusercontent.com/9707110/101859232-4747e200-3b39-11eb-95a3-c844d6e40abf.png)

```
Error Information
--- !ruby/exception:TypeError
message: no implicit conversion of Pathname into String
blamed_files:
- !ruby/object:Pathname
  path: "/home/app/webapp/assessmentConfig/15-213-hello.rb"
Stack Dump
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/home/app/webapp/app/helpers/assessment_autograde_core.rb:402:in `extend_config_module'
/home/app/webapp/app/controllers/assessments_controller.rb:406:in `show'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:194:in `process_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/usr/local/rvm/gems/ruby-2.6.6/gems/browser-timezone-rails-1.1.0/lib/browser-timezone-rails.rb:22:in `set_time_zone'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/activerecord-5.2.0/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:134:in `process'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionview-5.2.0/lib/action_view/rendering.rb:32:in `process'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_controller/metal.rb:191:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_controller/metal.rb:252:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `each'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `serve'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:840:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/rack-attack-6.2.2/lib/rack/attack.rb:156:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/exception_notification-4.4.0/lib/exception_notification/rack.rb:36:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/rack-ssl-enforcer-0.2.9/lib/rack/ssl-enforcer.rb:52:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/rack-attack-6.2.2/lib/rack/attack.rb:163:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/usr/local/rvm/gems/ruby-2.6.6/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:98:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/static.rb:127:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/actionpack-5.2.0/lib/action_dispatch/middleware/ssl.rb:74:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/engine.rb:524:in `call'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.6/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Steps To Reproduce**
1. Start docker-compose installation instance
2. Create a new course
3. Restart
4. Go to previously created course, this issue happens

**Current behavior**
As above

**Expected behavior**
Should not error

**Screenshots**

**Comment by fanpu** [comment]
I tried changing the following in `assessment.rb`:

```
  def config_file_path
    Rails.root.join("assessmentConfig", "#{course.name}-#{sanitized_name}.rb")
  end
```

to
```
  def config_file_path
    Rails.root.join("assessmentConfig", "#{course.name}-#{sanitized_name}.rb").to_s
  end
```

which resulted in a different error which now shows the real reason. It was because the assessmentConfig directory was not volume mapped in docker-compose.yml. When the volume mapping was added and I tried re-creating the courses and going through the previous steps again it worked.

**Comment by ugogon** [comment]
I have/had the same problem. Is this wanted behavior or an error? Should not the docker compose file get extended in this regard?
