### ISSUE TITLE
Missing bundler in docker base image (broken build)

### ISSUE THREAD

**Issue by pranayga** [autolab/Autolab#1448]
**Your environment**
Let us know details such as 
- Which institution's Autolab you are using (e.g. Carnegie Mellon's Autolab at https://autolab.andrew.cmu.edu/ etc)
    - Carnegie Mellon
- Operating system
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Commit hash (if relevant)
```
commit 2b2164e586490434d12ea8a5e021bc660deea1b1
```
- Ruby version (if relevant)
```
ruby-2.6.9
```
- Rails version (if relevant)
```
not relevant
```

**Steps To Reproduce**
```
git clone --recurse-submodules -j8 git://github.com/autolab/docker.git autolab-docker
cd autolab-docker
make update
make
docker-compose build
```

Make sure post update, `Autolab/` has the commit stated above.

**Current behavior**
```
Building autolab
Step 1/23 : FROM phusion/passenger-ruby26:2.1.0
2.1.0: Pulling from phusion/passenger-ruby26
35807b77a593: Already exists
0c7e1389008f: Already exists
49149f8e1683: Already exists
25ce01a09fa3: Pull complete
9efc8a879cff: Pull complete
Digest: sha256:5c576af162e0e4509911c02cc14b6da27de7ebcc59ff9a60289b1a3e5a0acdf2
Status: Downloaded newer image for phusion/passenger-ruby26:2.1.0
 ---> 15d3fee64ccc
Step 2/23 : MAINTAINER Autolab Development Team "autolab-dev@andrew.cmu.edu"
 ---> Running in 097989dc887c
Removing intermediate container 097989dc887c
 ---> a18e879016c3
Step 3/23 : RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
 ---> Running in cd45b4df1999
Removing intermediate container cd45b4df1999
 ---> c5f4b040a966
Step 4/23 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Running in 73440e08b1ef
Removing intermediate container 73440e08b1ef
 ---> 5c5b1043e214
Step 5/23 : RUN apt-get update && apt-get install -y   sqlite3   tzdata    shared-mime-info
 ---> Running in fae2b765607a
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Ign:3 https://oss-binaries.phusionpassenger.com/apt/passenger focal InRelease
Get:4 https://oss-binaries.phusionpassenger.com/apt/passenger focal Release [3,419 B]
Get:5 https://oss-binaries.phusionpassenger.com/apt/passenger focal Release.gpg [833 B]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/multiverse Sources [8,642 B]
Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/restricted Sources [33.6 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/main Sources [238 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal/restricted Sources [7,198 B]
Get:12 http://archive.ubuntu.com/ubuntu focal/universe Sources [12.3 MB]
Get:13 http://security.ubuntu.com/ubuntu focal-security/universe Sources [99.9 kB]
Get:14 https://oss-binaries.phusionpassenger.com/apt/passenger focal/main amd64 Packages [9,768 B]
Get:15 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [733 kB]
Get:16 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1,335 kB]
Get:17 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [828 kB]
Get:18 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [30.1 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal/main Sources [1,079 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal/multiverse Sources [208 kB]
Get:21 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:22 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:23 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1,275 kB]
Get:24 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:25 http://archive.ubuntu.com/ubuntu focal-updates/main Sources [567 kB]
Get:26 http://archive.ubuntu.com/ubuntu focal-updates/restricted Sources [34.6 kB]
Get:27 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Sources [21.8 kB]
Get:28 http://archive.ubuntu.com/ubuntu focal-updates/universe Sources [265 kB]
Get:29 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [797 kB]
Get:30 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1,758 kB]
Get:31 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [33.6 kB]
Get:32 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,108 kB]
Get:33 http://archive.ubuntu.com/ubuntu focal-backports/main Sources [7,512 B]
Get:34 http://archive.ubuntu.com/ubuntu focal-backports/universe Sources [4,956 B]
Get:35 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [50.8 kB]
Get:36 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [21.7 kB]
Fetched 35.0 MB in 5s (7,130 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
sqlite3 is already the newest version (3.31.1-4ubuntu0.2).
The following NEW packages will be installed:
  shared-mime-info
The following packages will be upgraded:
  tzdata
1 upgraded, 1 newly installed, 0 to remove and 18 not upgraded.
Need to get 725 kB of archives.
After this operation, 2,716 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 shared-mime-info amd64 1.15-1 [430 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 tzdata all 2021e-0ubuntu0.20.04 [295 kB]
Preconfiguring packages ...
Fetched 725 kB in 1s (652 kB/s)
Selecting previously unselected package shared-mime-info.
(Reading database ... 20939 files and directories currently installed.)
Preparing to unpack .../shared-mime-info_1.15-1_amd64.deb ...
Unpacking shared-mime-info (1.15-1) ...
Preparing to unpack .../tzdata_2021e-0ubuntu0.20.04_all.deb ...
Unpacking tzdata (2021e-0ubuntu0.20.04) over (2021a-0ubuntu0.20.04) ...
Setting up tzdata (2021e-0ubuntu0.20.04) ...

Current default time zone: 'America/New_York'
Local time is now:      Sat Dec 18 18:59:23 EST 2021.
Universal Time is now:  Sat Dec 18 23:59:23 UTC 2021.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Setting up shared-mime-info (1.15-1) ...
Removing intermediate container fae2b765607a
 ---> 2e483d58cec3
Step 6/23 : RUN rm -f /etc/service/nginx/down
 ---> Running in 4850ec8dabb1
Removing intermediate container 4850ec8dabb1
 ---> 4ee765fc3ab5
Step 7/23 : RUN rm /etc/nginx/sites-enabled/default
 ---> Running in 06153649fb68
Removing intermediate container 06153649fb68
 ---> dbd11d2f3aa2
Step 8/23 : WORKDIR /tmp
 ---> Running in cb950249ba5a
Removing intermediate container cb950249ba5a
 ---> a9434a9b932a
Step 9/23 : ADD Gemfile .
 ---> b4645acae7ad
Step 10/23 : ADD Gemfile.lock .
 ---> a15207c339c9
Step 11/23 : RUN chown app:app Gemfile Gemfile.lock
 ---> Running in 247a19b782e8
Removing intermediate container 247a19b782e8
 ---> 43635763e6b4
Step 12/23 : USER app
 ---> Running in 87775422adcb
Removing intermediate container 87775422adcb
 ---> 11733b7cc394
Step 13/23 : RUN bundle install
 ---> Running in 4a9e21d3c2b0
/usr/local/rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.2.31) required by your /tmp/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.2.31`
        from /usr/local/rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
        from /usr/local/rvm/rubies/ruby-2.6.9/bin/bundle:30:in `<main>'
```

**Expected behavior**
```
Building autolab
Step 1/24 : FROM phusion/passenger-ruby26:2.0.0
 ---> 0d204e05208d
Step 2/24 : MAINTAINER Autolab Development Team "autolab-dev@andrew.cmu.edu"
 ---> Using cache
 ---> b387aec2d612
Step 3/24 : RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
 ---> Using cache
 ---> 1200ab0232c5
Step 4/24 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> b9901f25de08
Step 5/24 : RUN apt-get update && apt-get install -y   sqlite3   tzdata    shared-mime-info
 ---> Using cache
 ---> 0597b37eb4ce
Step 6/24 : RUN gem install bundler:2.2.31
 ---> Running in 2aef1c8c6e21
Successfully installed bundler-2.2.31
1 gem installed
Removing intermediate container 2aef1c8c6e21
 ---> 452359ed7112
Step 7/24 : RUN rm -f /etc/service/nginx/down
 ---> Running in dca7d14ab8bc
Removing intermediate container dca7d14ab8bc
 ---> a6e7f31b0a67
Step 8/24 : RUN rm /etc/nginx/sites-enabled/default
 ---> Running in 6af63cfa816d
Removing intermediate container 6af63cfa816d
 ---> d3d1d7f6c352
Step 9/24 : WORKDIR /tmp
 ---> Running in b354ccd4e10d
Removing intermediate container b354ccd4e10d
 ---> 90a30e0da0bf
Step 10/24 : ADD Gemfile .
 ---> 6bb45b01b9e1
Step 11/24 : ADD Gemfile.lock .
 ---> ad1b9a3ec7b0
Step 12/24 : RUN chown app:app Gemfile Gemfile.lock
 ---> Running in ce724f215ef7
Removing intermediate container ce724f215ef7
 ---> febb54587cfe
Step 13/24 : USER app
 ---> Running in 901b6c6282ae
Removing intermediate container 901b6c6282ae
 ---> 1ba25aead1f2
Step 14/24 : RUN bundle install
 ---> Running in 296e2545a359
Fetching gem metadata from https://rubygems.org/.........
Using rake 13.0.6
Fetching Ascii85 1.0.3
Fetching concurrent-ruby 1.1.9
Installing Ascii85 1.0.3
Installing concurrent-ruby 1.1.9
Fetching minitest 5.14.4
Installing minitest 5.14.4
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching builder 3.2.4
Installing builder 3.2.4
Fetching erubi 1.10.0
Installing erubi 1.10.0
Fetching mini_portile2 2.6.1
Fetching racc 1.6.0
Installing mini_portile2 2.6.1
Installing racc 1.6.0 with native extensions
Fetching crass 1.0.6
Installing crass 1.0.6
Using rack 2.2.3
Fetching nio4r 2.5.8
Installing nio4r 2.5.8 with native extensions
Fetching websocket-extensions 0.1.5
Installing websocket-extensions 0.1.5
Fetching mini_mime 1.1.2
Installing mini_mime 1.1.2
Fetching arel 9.0.0
Installing arel 9.0.0
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching afm 0.2.2
Installing afm 0.2.2
Fetching ast 2.4.2
Installing ast 2.4.2
Fetching execjs 2.8.1
Installing execjs 2.8.1
Fetching bcrypt 3.1.16
Installing bcrypt 3.1.16 with native extensions
Fetching coderay 1.1.3
Installing coderay 1.1.3
Fetching debug_inspector 1.1.0
Installing debug_inspector 1.1.0 with native extensions
Fetching ffi 1.15.4
Installing ffi 1.15.4 with native extensions
Fetching method_source 1.0.0
Installing method_source 1.0.0
Fetching thor 1.1.0
Installing thor 1.1.0
Using bundler 2.2.31
Fetching byebug 11.1.3
Installing byebug 11.1.3 with native extensions
Fetching matrix 0.4.2
Installing matrix 0.4.2
Fetching regexp_parser 2.1.1
Installing regexp_parser 2.1.1
Fetching docile 1.1.5
Installing docile 1.1.5
Fetching json 2.6.1
Installing json 2.6.1 with native extensions
Fetching simplecov-html 0.10.2
Installing simplecov-html 0.10.2
Fetching coffee-script-source 1.12.2
Installing coffee-script-source 1.12.2
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching daemons 1.4.1
Installing daemons 1.4.1
Fetching database_cleaner-core 2.0.1
Installing database_cleaner-core 2.0.1
Fetching orm_adapter 0.5.0
Installing orm_adapter 0.5.0
Fetching diff-lcs 1.4.4
Installing diff-lcs 1.4.4
Fetching dotenv 2.7.6
Installing dotenv 2.7.6
Fetching dynamic_form 1.1.4
Installing dynamic_form 1.1.4
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Fetching faraday-em_http 1.0.0
Installing faraday-em_http 1.0.0
Fetching faraday-em_synchrony 1.0.0
Installing faraday-em_synchrony 1.0.0
Fetching faraday-excon 1.1.0
Installing faraday-excon 1.1.0
Fetching faraday-httpclient 1.0.1
Fetching faraday-net_http 1.0.1
Installing faraday-httpclient 1.0.1
Installing faraday-net_http 1.0.1
Fetching faraday-net_http_persistent 1.2.0
Installing faraday-net_http_persistent 1.2.0
Fetching faraday-patron 1.0.0
Installing faraday-patron 1.0.0
Fetching faraday-rack 1.0.0
Fetching multipart-post 2.1.1
Installing faraday-rack 1.0.0
Installing multipart-post 2.1.1
Fetching ruby2_keywords 0.0.5
Fetching tilt 2.0.10
Installing tilt 2.0.10
Installing ruby2_keywords 0.0.5
Fetching hashdiff 1.0.1
Installing hashdiff 1.0.1
Fetching hashery 2.1.2
Installing hashery 2.1.2
Fetching hashie 5.0.0
Installing hashie 5.0.0
Fetching mime-types-data 3.2021.0901
Fetching multi_xml 0.6.0
Installing mime-types-data 3.2021.0901
Installing multi_xml 0.6.0
Fetching jwt 2.3.0
Installing jwt 2.3.0
Fetching libv8-node 15.14.0.1 (x86_64-linux-musl)
Fetching lockbox 0.6.6
Installing lockbox 0.6.6
Fetching multi_json 1.15.0
Installing multi_json 1.15.0
Fetching mysql2 0.4.10
Installing mysql2 0.4.10 with native extensions
Installing libv8-node 15.14.0.1 (x86_64-linux-musl)
Fetching net-ldap 0.17.0
Installing net-ldap 0.17.0
Fetching newrelic_rpm 8.1.0
Installing newrelic_rpm 8.1.0
Fetching parallel 1.21.0
Installing parallel 1.21.0
Fetching ruby-rc4 0.1.5
Installing ruby-rc4 0.1.5
Fetching ttfunk 1.0.3
Installing ttfunk 1.0.3
Fetching populator 1.0.0
Installing populator 1.0.0
Fetching rack-ssl-enforcer 0.2.9
Installing rack-ssl-enforcer 0.2.9
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching rdoc 6.3.3
Installing rdoc 6.3.3
Fetching rspec-support 3.10.3
Installing rspec-support 3.10.3
Fetching ruby-progressbar 1.11.0
Installing ruby-progressbar 1.11.0
Fetching unicode-display_width 2.1.0
Installing unicode-display_width 2.1.0
Fetching rubyzip 2.3.2
Installing rubyzip 2.3.2
Fetching slack-notifier 2.4.0
Installing slack-notifier 2.4.0
Fetching spring 3.0.0
Installing spring 3.0.0
Fetching sqlite3 1.3.13
Installing sqlite3 1.3.13 with native extensions
Fetching yard 0.9.26
Installing yard 0.9.26
Fetching tzinfo 1.2.9
Installing tzinfo 1.2.9
Fetching i18n 1.8.11
Installing i18n 1.8.11
Fetching rack-test 1.1.0
Installing rack-test 1.1.0
Fetching sprockets 4.0.2
Installing sprockets 4.0.2
Fetching warden 1.2.9
Installing warden 1.2.9
Fetching rack-protection 2.1.0
Installing rack-protection 2.1.0
Fetching rack-attack 6.5.0
Installing rack-attack 6.5.0
Fetching nokogiri 1.12.5 (x86_64-linux)
Installing nokogiri 1.12.5 (x86_64-linux)
Fetching websocket-driver 0.7.5
Installing websocket-driver 0.7.5 with native extensions
Fetching mail 2.7.1
Installing mail 2.7.1
Fetching addressable 2.8.0
Installing addressable 2.8.0
Fetching parser 3.0.2.0
Fetching autoprefixer-rails 10.3.3.0
Installing parser 3.0.2.0
Installing autoprefixer-rails 10.3.3.0
Fetching terser 1.1.7
Fetching better_errors 2.9.1
Installing terser 1.1.7
Installing better_errors 2.9.1
Fetching binding_of_caller 1.0.0
Installing binding_of_caller 1.0.0
Fetching sassc 2.4.0
Fetching coffee-script 2.4.1
Installing sassc 2.4.0 with native extensions
Installing coffee-script 2.4.1
Fetching crack 0.4.5
Installing crack 0.4.5
Fetching thin 1.8.1
Installing thin 1.8.1 with native extensions
Fetching simplecov 0.13.0
Installing simplecov 0.13.0
Fetching faraday 1.8.0
Installing faraday 1.8.0
Fetching mime-types 3.3.1
Installing mime-types 3.3.1
Fetching mini_racer 0.4.0
Installing mini_racer 0.4.0 with native extensions
Fetching pdf-reader 1.4.1
Installing pdf-reader 1.4.1
Fetching sdoc 2.2.0
Installing sdoc 2.2.0
Fetching rspec-core 3.10.1
Installing rspec-core 3.10.1
Fetching rspec-expectations 3.10.1
Installing rspec-expectations 3.10.1
Fetching rspec-mocks 3.10.2
Installing rspec-mocks 3.10.2
Fetching tzinfo-data 1.2021.5
Installing tzinfo-data 1.2021.5
Fetching activesupport 5.2.0
Installing activesupport 5.2.0
Fetching omniauth 2.0.4
Installing omniauth 2.0.4
Fetching loofah 2.12.0
Installing loofah 2.12.0
Fetching mimemagic 0.3.10
Installing mimemagic 0.3.10 with native extensions
Fetching xpath 3.2.0
Installing xpath 3.2.0
Fetching rubocop-ast 1.13.0
Installing rubocop-ast 1.13.0
Fetching materialize-sass 1.0.0
Fetching webmock 3.14.0
Installing materialize-sass 1.0.0
Installing webmock 3.14.0
Fetching codeclimate-test-reporter 1.0.9
Installing codeclimate-test-reporter 1.0.9
Fetching oauth2 1.4.7
Fetching sawyer 0.8.2
Installing oauth2 1.4.7
Installing sawyer 0.8.2
Fetching httparty 0.20.0
Fetching bootstrap-sass 3.4.1
Installing httparty 0.20.0
Installing bootstrap-sass 3.4.1
Fetching prawn 0.13.0
Fetching rails-dom-testing 2.0.3
Installing rails-dom-testing 2.0.3
Installing prawn 0.13.0
Fetching globalid 0.5.2
Installing globalid 0.5.2
Fetching activemodel 5.2.0
Installing activemodel 5.2.0
Fetching factory_bot 6.2.0
Installing factory_bot 6.2.0
Fetching jbuilder 2.11.2
Installing jbuilder 2.11.2
Fetching omniauth-shibboleth 1.3.0
Installing omniauth-shibboleth 1.3.0
Fetching rails-html-sanitizer 1.4.2
Installing rails-html-sanitizer 1.4.2
Fetching capybara 3.36.0
Fetching rubocop 1.22.3
Installing capybara 3.36.0
Installing rubocop 1.22.3
Fetching marcel 0.3.3
Installing marcel 0.3.3
Fetching octokit 4.21.0
Installing octokit 4.21.0
Fetching omniauth-oauth2 1.7.2
Installing omniauth-oauth2 1.7.2
Fetching activejob 5.2.0
Installing activejob 5.2.0
Fetching activerecord 5.2.0
Installing activerecord 5.2.0
Fetching actionview 5.2.0
Installing actionview 5.2.0
Fetching omniauth-facebook 9.0.0
Installing omniauth-facebook 9.0.0
Fetching omniauth-google-oauth2 1.0.0
Installing omniauth-google-oauth2 1.0.0
Fetching database_cleaner-active_record 2.0.1
Installing database_cleaner-active_record 2.0.1
Fetching actionpack 5.2.0
Installing actionpack 5.2.0
Fetching database_cleaner 2.0.1
Installing database_cleaner 2.0.1
Fetching actioncable 5.2.0
Fetching actionmailer 5.2.0
Installing actionmailer 5.2.0
Installing actioncable 5.2.0
Fetching activestorage 5.2.0
Installing activestorage 5.2.0
Fetching railties 5.2.0
Installing railties 5.2.0
Fetching sprockets-rails 3.3.0
Installing sprockets-rails 3.3.0
Fetching exception_notification 4.4.3
Installing exception_notification 4.4.3
Fetching js_cookie_rails 2.2.0
Fetching momentjs-rails 2.15.1
Installing js_cookie_rails 2.2.0
Installing momentjs-rails 2.15.1
Fetching rails 5.2.0
Installing rails 5.2.0
Fetching coffee-rails 5.0.0
Installing coffee-rails 5.0.0
Fetching responders 3.0.1
Installing responders 3.0.1
Fetching doorkeeper 5.5.4

  Please read the changelog for details:

  https://github.com/prawnpdf/prawn/wiki/CHANGELOG


  ********************************************

Post-install message from rubyzip:
RubyZip 3.0 is coming!
**********************

The public API of some Rubyzip classes has been modernized to use named
parameters for optional arguments. Please check your usage of the
following classes:
  * `Zip::File`
  * `Zip::Entry`
  * `Zip::InputStream`
  * `Zip::OutputStream`

Please ensure that your Gemfiles and .gemspecs are suitably restrictive
to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
See https://github.com/rubyzip/rubyzip for details. The Changelog also
lists other enhancements and bugfixes that have been implemented since
version 2.3.0.
Removing intermediate container 296e2545a359
 ---> 508f9ca29104
Step 15/24 : RUN mkdir /home/app/webapp
 ---> Running in 4dd5a71db69c
Removing intermediate container 4dd5a71db69c
 ---> e516032350c8
Step 16/24 : WORKDIR /home/app/webapp
 ---> Running in e5d783df8544
Removing intermediate container e5d783df8544
 ---> 6bdfb429c79e
Step 17/24 : ADD . /home/app/webapp
 ---> c947ac06eeb7
Step 18/24 : USER root
 ---> Running in b7f74d26e8db
Removing intermediate container b7f74d26e8db
 ---> 7c5d456c5115
Step 19/24 : RUN mkdir -p /home/app/webapp/log &&   touch /home/app/webapp/log/production.log &&   chmod 0664 /home/app/webapp/log/production.log &&   chown -R app:app .
 ---> Running in cd39eff47ba1
Removing intermediate container cd39eff47ba1
5533686320ac5b48cdb772.css
I, [2021-12-18T19:12:19.346679 #8]  INFO -- : Writing /home/app/webapp/public/assets/metricsgraphics-6bcb3144ec016cc87e64c964ae824f517a89967ec75533686320ac5b48cdb772.css.gz
I, [2021-12-18T19:12:19.349969 #8]  INFO -- : Writing /home/app/webapp/public/assets/users-1aee353eb05af27ab49fb07fd738ffbe7b4add23e77268d2541f7fc6a0265a37.scss
I, [2021-12-18T19:12:19.352522 #8]  INFO -- : Writing /home/app/webapp/public/assets/users-1aee353eb05af27ab49fb07fd738ffbe7b4add23e77268d2541f7fc6a0265a37.scss.gz
I, [2021-12-18T19:12:19.352965 #8]  INFO -- : Writing /home/app/webapp/public/assets/annotations-e677d09a52c35e593f43429de7ca83682a4b4eab3f0e260c711a9539dd2c3b3a.js
I, [2021-12-18T19:12:19.353254 #8]  INFO -- : Writing /home/app/webapp/public/assets/annotations-e677d09a52c35e593f43429de7ca83682a4b4eab3f0e260c711a9539dd2c3b3a.js.gz
I, [2021-12-18T19:12:19.355647 #8]  INFO -- : Writing /home/app/webapp/public/assets/chroma.min-db4156841920b6ec9d90d0c5eca14f989a9ab5dee4922c62b45c345dda7e8c11.js
I, [2021-12-18T19:12:19.355926 #8]  INFO -- : Writing /home/app/webapp/public/assets/chroma.min-db4156841920b6ec9d90d0c5eca14f989a9ab5dee4922c62b45c345dda7e8c11.js.gz
I, [2021-12-18T19:12:19.356339 #8]  INFO -- : Writing /home/app/webapp/public/assets/gradesheet.js-146b42e1bb3f5b4c7c2f83352893ad2608e606813428223dd564d7fbcea9e8dd.erb
I, [2021-12-18T19:12:19.356717 #8]  INFO -- : Writing /home/app/webapp/public/assets/gradesheet.js-146b42e1bb3f5b4c7c2f83352893ad2608e606813428223dd564d7fbcea9e8dd.erb.gz
I, [2021-12-18T19:12:19.356945 #8]  INFO -- : Writing /home/app/webapp/public/assets/initialize_tooltips-a67156c019a0a1d0860f51917b1611cb66b00dd3b05db236a625d57c623b576a.js
I, [2021-12-18T19:12:19.357371 #8]  INFO -- : Writing /home/app/webapp/public/assets/initialize_tooltips-a67156c019a0a1d0860f51917b1611cb66b00dd3b05db236a625d57c623b576a.js.gz
I, [2021-12-18T19:12:19.357987 #8]  INFO -- : Writing /home/app/webapp/public/assets/lodash_set_template_style-5e043f8662f04701d913622a33c4843ab7adc953b725aab2e8b85c099bf73613.js
I, [2021-12-18T19:12:19.363485 #8]  INFO -- : Writing /home/app/webapp/public/assets/lodash_set_template_style-5e043f8662f04701d913622a33c4843ab7adc953b725aab2e8b85c099bf73613.js.gz
I, [2021-12-18T19:12:19.369402 #8]  INFO -- : Writing /home/app/webapp/public/assets/pdf.worker-70de16ae037414b9be685d830d0e95b590333f077b2ec46d29f54fbd05ccac1b.js
I, [2021-12-18T19:12:19.370890 #8]  INFO -- : Writing /home/app/webapp/public/assets/pdf.worker-70de16ae037414b9be685d830d0e95b590333f077b2ec46d29f54fbd05ccac1b.js.gz
I, [2021-12-18T19:12:19.375518 #8]  INFO -- : Writing /home/app/webapp/public/assets/table-b67fd1bef8c2052968a360051eae26f57c4dd953c0e3a1a54de91d7818844fd1.js
I, [2021-12-18T19:12:19.382047 #8]  INFO -- : Writing /home/app/webapp/public/assets/table-b67fd1bef8c2052968a360051eae26f57c4dd953c0e3a1a54de91d7818844fd1.js.gz
I, [2021-12-18T19:12:19.387773 #8]  INFO -- : Writing /home/app/webapp/public/assets/app-level-b034bc4471a40739b4be7cfcbc6a5fb9e4cccea6034a48a377b4665fafbf7aba.js
I, [2021-12-18T19:12:19.388798 #8]  INFO -- : Writing /home/app/webapp/public/assets/app-level-b034bc4471a40739b4be7cfcbc6a5fb9e4cccea6034a48a377b4665fafbf7aba.js.gz
I, [2021-12-18T19:12:19.391981 #8]  INFO -- : Writing /home/app/webapp/public/assets/confirm_discard_changes-841d390f951b995a2f6513cfb33f36b41ae8cebb45ff98462e149a6f9bac71c1.css.gz
I, [2021-12-18T19:12:19.703572 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.grid-f7e8f87cb9e592e843025d6e5d59bd625a5453f850ce34748b9e3d1929829de9.css
I, [2021-12-18T19:12:19.704199 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.grid-f7e8f87cb9e592e843025d6e5d59bd625a5453f850ce34748b9e3d1929829de9.css.gz
I, [2021-12-18T19:12:19.704786 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/controls/slick.columnpicker-0758c7ae9569c49dab1d320eed86768f9350fb0c018c89e9baaafc3bdee67798.css
I, [2021-12-18T19:12:19.705253 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/controls/slick.columnpicker-0758c7ae9569c49dab1d320eed86768f9350fb0c018c89e9baaafc3bdee67798.css.gz
I, [2021-12-18T19:12:19.712585 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.core-5ee167356fc538c95ee12988bae779dda3f36dff8b5e56cabd7e21e8ca4a7407.js
I, [2021-12-18T19:12:19.713251 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.core-5ee167356fc538c95ee12988bae779dda3f36dff8b5e56cabd7e21e8ca4a7407.js.gz
I, [2021-12-18T19:12:19.714016 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.grid-5c7dc5e340372f899f7ba92bf28e203641bb6965aa440b5e540bd9dc72cef4e9.js
I, [2021-12-18T19:12:19.714610 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.grid-5c7dc5e340372f899f7ba92bf28e203641bb6965aa440b5e540bd9dc72cef4e9.js.gz
I, [2021-12-18T19:12:19.715435 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.dataview-bb48098c93b8264cdb7b36278f70234b2cebccc3ed68282a8db9e1f9b08c00bf.js
I, [2021-12-18T19:12:19.716273 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/slick.dataview-bb48098c93b8264cdb7b36278f70234b2cebccc3ed68282a8db9e1f9b08c00bf.js.gz
I, [2021-12-18T19:12:19.717052 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/controls/slick.columnpicker-19372de8695820e1e3666b815ed507fcf458b853cfbfe05b3e7edaad6869d811.js
I, [2021-12-18T19:12:19.717779 #8]  INFO -- : Writing /home/app/webapp/public/assets/SlickGrid/2.02/controls/slick.columnpicker-19372de8695820e1e3666b815ed507fcf458b853cfbfe05b3e7edaad6869d811.js.gz
Removing intermediate container 50ca967f3861
 ---> 633611cbb2fd
Step 22/24 : USER root
 ---> Running in 51cfa1b4cba4
Removing intermediate container 51cfa1b4cba4
 ---> e49ede3c229a
Step 23/24 : RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in b327be726373
Removing intermediate container b327be726373
 ---> 69ceeafe58f6
Step 24/24 : CMD ["/sbin/my_init"]
 ---> Running in 9767c4c1da7b
Removing intermediate container 9767c4c1da7b
 ---> 90c67111954c

Successfully built 90c67111954c
```

**Screenshots**

<img width="1146" alt="Screen Shot 2021-12-18 at 4 21 03 PM" src="https://user-images.githubusercontent.com/54598374/146659120-03eec2d0-22cf-4014-999c-0bf4e65bb115.png">

**Comment by victorhuangwq** [comment]
Issue addressed by #1447.
