### ISSUE TITLE
problems connecting to Tango (TangoClient::TangoException)

### ISSUE THREAD

**Issue by msherr** [autolab/Autolab#666]
Hi all,

I'm installing Autolab and have made some good progress, but am getting stuck on connecting to the autograder.  I've installed Tango outside of Docker and have verified from within the Autolab docker container that I can access it (tested via curl).  When I go to https://site.com/courses/cosc150-test/jobs/tango_status, I receive the following:

Error Information
--- !ruby/exception:TangoClient::TangoException
message: Unexpected error with Tango (undefined method `+' for nil:NilClass).
Stack Dump
/home/app/webapp/lib/tango_client.rb:27:in `rescue in handle_exceptions'
/home/app/webapp/lib/tango_client.rb:19:in `handle_exceptions'
/home/app/webapp/lib/tango_client.rb:60:in `info'
/home/app/webapp/app/controllers/jobs_controller.rb:163:in `tango_status'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'

Looking at the cited source files, I can't see anything obviously wrong, but I unfortunately don't speak Ruby.  Any help would be gratefully appreciated.

Thank you,
Micah

**Comment by msherr** [comment]
I solved my own issue.

When copying from Autolab/config/autogradeConfig.rb.template to Autolab/config/autogradeConfig.rb, I blindly substituted ENV["RESTFUL_HOST"] with ENV["ACTUAL_HOSTNAME"].  But ENV["ACTUAL_HOSTNAME"] isn't an actual environment variable.  So I hardcoded (without the ENV[...]) the correct values and that fixed the problem.

I'm not quite sure why the template has these as environment variables, but I'm sure there's a good reason.  

Hopefully someone can learn from my silly mistake.

Best,
Micah
