### ISSUE TITLE
500 Internal Error on sample homework ruby/exception:TypeError message: no implicit conversion of Pathname into String

### ISSUE THREAD

**Issue by RobbieTheK** [autolab/Autolab#996]
new install of Ubuntu 18.04 64 bit, clicking any AutoPopulated (SEM) results in the below.
uname -a
`Linux sysadmin 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Error Information**
```
--- !ruby/exception:TypeError
message: no implicit conversion of Pathname into String
blamed_files:
- !ruby/object:Pathname
  path: "/home/app/webapp/assessmentConfig/AutoPopulated-homework5.rb"
```

**Stack Dump**
```
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/app/webapp/app/controllers/assessment/autograde.rb:516:in `extend_config_module'
/home/app/webapp/app/controllers/assessments_controller.rb:393:in `show'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:313:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
/var/lib/gems/2.2.0/gems/browser-timezone-rails-1.0.1/lib/browser-timezone-rails.rb:15:in `set_time_zone'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:312:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:312:in `block in halting'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `block in around'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
/var/lib/gems/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:32:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:140:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
/var/lib/gems/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
/var/lib/gems/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/query_cache.rb:36:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `public_send'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `method_missing'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

**Comment by RobbieTheK** [comment]
The errors on homework and labs appear to have gone away but still seeing the following when clicking /courses/AutoPopulated/assessments/labtemplate, so under Category Autograde, Lab Template:

```
--- !ruby/exception:TypeError
message: no implicit conversion of Pathname into String
blamed_files:
- !ruby/object:Pathname
  path: "/home/app/webapp/assessmentConfig/AutoPopulated-labtemplate.rb"
```
**Stack Dump**
```
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/home/app/webapp/app/controllers/assessment/autograde.rb:516:in `extend_config_module'
/home/app/webapp/app/controllers/assessments_controller.rb:393:in `show'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:313:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
/var/lib/gems/2.2.0/gems/browser-timezone-rails-1.0.1/lib/browser-timezone-rails.rb:15:in `set_time_zone'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:312:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:312:in `block in halting'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `block in around'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
/var/lib/gems/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:32:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:140:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
/var/lib/gems/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
/var/lib/gems/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/query_cache.rb:36:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `public_send'
/var/lib/gems/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `method_missing'
/var/lib/gems/2.2.0/gems/newrelic_rpm-3.17.2.327/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start
```

Is this the time of year students are not supporting any updates, being summer? I noticed the  autolab@myschool.edu  emails bounce back too.

**Comment by victorhuangwq** [comment]
Seems to be a stale issue. Let me know if the issue still persist in the latest master.
